Disabling FEApp due to Boost error?
It would seem that FEApp using Sacado is not working with the version of Boost
we currently have on our system.  It generates an error like:

[ 97%] Building CXX object demos/FEApp/example/piro/CMakeFiles/FEApp_SGSolve.dir/FEApp_SGSolve.cpp.o
In file included from /localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/TriKota/Dakota/src/PRPMultiIndex.hpp:24:0,
                 from /localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/TriKota/Dakota/src/ApplicationInterface.hpp:19,
                 from /localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/TriKota/Dakota/src/DirectApplicInterface.hpp:19,
                 from /localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/TriKota/src/TriKota_DirectApplicInterface.hpp:37,
                 from /localhome/8vt/PROJECTS/Trilinos.base/Trilinos/demos/FEApp/example/piro/FEApp_Dakota.cpp:54:
/opt/gcc-4.5.1/tpls/boost-1.46.1/include/boost/multi_index/ordered_index.hpp: In member function ‘void boost::multi_index::detail::ordered_index<KeyFromValue, Compare, SuperMeta, TagList, Category>::load_(Archive&, unsigned int, const index_loader_type&, boost::multi_index::detail::ordered_non_unique_tag)’:
/opt/gcc-4.5.1/tpls/boost-1.46.1/include/boost/multi_index/ordered_index.hpp:1203:53: error: reference to ‘_1’ is ambiguous
/localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/sacado/src/mpl/Sacado_mpl_placeholders.hpp:97:22: error: candidates are: typedef struct Sacado::mpl::arg<1> Sacado::mpl::placeholders::_1
/opt/gcc-4.5.1/tpls/boost-1.46.1/include/boost/bind/placeholders.hpp:55:15: error:                 boost::arg<1> {anonymous}::_1
/opt/gcc-4.5.1/tpls/boost-1.46.1/include/boost/multi_index/ordered_index.hpp:1203:56: error: reference to ‘_2’ is ambiguous
/localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/sacado/src/mpl/Sacado_mpl_placeholders.hpp:98:22: error: candidates are: typedef struct Sacado::mpl::arg<2> Sacado::mpl::placeholders::_2
/opt/gcc-4.5.1/tpls/boost-1.46.1/include/boost/bind/placeholders.hpp:56:15: error:                 boost::arg<2> {anonymous}::_2
/localhome/8vt/PROJECTS/Trilinos.base/Trilinos/demos/FEApp/example/piro/FEApp_SGAnalysis.cpp: In function ‘int main(int, char**)’:
/localhome/8vt/PROJECTS/Trilinos.base/Trilinos/demos/FEApp/example/piro/FEApp_SGAnalysis.cpp:160:9: warning: unused variable ‘status’ [-Wunused-variable]
[ 97%] Building CXX object packages/Sundance/src-core/CMakeFiles/sundanceCore.dir/InternalExprs/SundanceUnaryExpr.cpp.o
/localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/TriKota/Dakota/packages/pecos/src/pecos_global_defs.hpp: At global scope:
/localhome/8vt/PROJECTS/Trilinos.base/Trilinos/packages/TriKota/Dakota/packages/pecos/src/pecos_global_defs.hpp:26:14: warning: ‘Pecos::PI’ defined but not used [-Wunused-variable]
make[2]: *** [demos/FEApp/example/piro/CMakeFiles/FEApp_Dakota.dir/FEApp_Dakota.cpp.o] Error 1

Sorry, FEApp is getting disabled too :-(