Kokkos: Compat: Fixed weird build errors with C++11.
With GCC 4.8.2 and C++11 enabled, I got weird build errors in some
functions in KokkosCompat.  See the sample error message below.  The
implementations of the functions in question were calling
std::make_pair<Ordinal, Ordinal> (for Ordinal = long unsigned int)
with Ordinal arguments.  However, the compiler was confusing them with
Ordinal&&.  (The double ampersand means an "rvalue reference," which
is silly for a built-in integer type, but legal.)  I fixed this by
making the Ordinal inputs of the affected functions "const Ordinal",
so that the compiler would not confuse them with Ordinal&&.

Here is an example error:

In file included from ${TRILINOS_SRC_DIR}/packages/kokkos/compat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:24:0,
                 from ${TRILINOS_SRC_DIR}/packages/kokkos/classic/NodeAPI/Kokkos_DefaultNode.hpp:61,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_Map_decl.hpp:45,
                 from ${TRILINOS_SRC_DIR}/CHECKIN/MPI_DEBUG_KOKKOS_REFACTOR/packages/tpetra/src/Tpetra_Map.hpp:1,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject_decl.hpp:46,
                 from ${TRILINOS_SRC_DIR}/CHECKIN/MPI_DEBUG_KOKKOS_REFACTOR/packages/tpetra/src/Tpetra_DistObject.hpp:1,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject.cpp:44:
${TRILINOS_SRC_DIR}/packages/kokkos/compat/src/KokkosCompat_View.hpp: In instantiation of ‘Kokkos::View<T*, L, D, M> Kokkos::Compat::subview_offset(const Kokkos::View<T*, L, D, M>&, Ordinal, Ordinal) [with T = const long unsigned int; L = Kokkos::LayoutRight; D = Kokkos::Threads; M = void; Ordinal = long unsigned int; typename Kokkos::ViewTraits<T*, L, D, M>::specialize = Kokkos::Impl::ViewDefault]’:
${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_Distributor.hpp:2167:71:   required from ‘void Tpetra::Distributor::doPosts(const Kokkos::View<const T*, L, D, M>&, size_t, const Kokkos::View<T*, L, D, M>&) [with Packet = long unsigned int; Layout = Kokkos::LayoutRight; Device = Kokkos::Threads; Mem = void; typename Kokkos::ViewTraits<const T*, L, D, M>::specialize = Kokkos::Impl::ViewDefault; size_t = long unsigned int; typename Kokkos::ViewTraits<T*, L, D, M>::specialize = Kokkos::Impl::ViewDefault]’
${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_Distributor.hpp:1914:5:   required from ‘void Tpetra::Distributor::doPostsAndWaits(const Kokkos::View<const T*, L, D, M>&, size_t, const Kokkos::View<T*, L, D, M>&) [with Packet = long unsigned int; Layout = Kokkos::LayoutRight; Device = Kokkos::Threads; Mem = void; typename Kokkos::ViewTraits<const T*, L, D, M>::specialize = Kokkos::Impl::ViewDefault; size_t = long unsigned int; typename Kokkos::ViewTraits<T*, L, D, M>::specialize = Kokkos::Impl::ViewDefault]’
${TRILINOS_SRC_DIR}/packages/tpetra/src/kokkos_refactor/Tpetra_KokkosRefactor_DistObject_def.hpp:868:13:   required from ‘void Tpetra::DistObject<Packet, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<Device> >::doTransferNew(const Tpetra::SrcDistObject&, Tpetra::CombineMode, size_t, const Teuchos::ArrayView<const Packet>&, const Teuchos::ArrayView<const Packet>&, const Teuchos::ArrayView<const Packet>&, const Teuchos::ArrayView<const Packet>&, Tpetra::Distributor&, Tpetra::DistObject<Packet, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<Device> >::ReverseOption) [with Packet = double; LocalOrdinal = int; GlobalOrdinal = int; Device = Kokkos::Threads; size_t = long unsigned int]’
${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject.cpp:55:2:   required from here
${TRILINOS_SRC_DIR}/packages/kokkos/compat/src/KokkosCompat_View.hpp:193:65: error: no matching function for call to ‘make_pair(long unsigned int&, long unsigned int)’
         view, std::make_pair<Ordinal,Ordinal>(offset,offset+size));
                                                                 ^
${TRILINOS_SRC_DIR}/packages/kokkos/compat/src/KokkosCompat_View.hpp:193:65: note: candidate is:
In file included from ${PKG_DIR}/gcc-4.8.2/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from ${PKG_DIR}/gcc-4.8.2/include/c++/4.8.2/bits/char_traits.h:39,
                 from ${PKG_DIR}/gcc-4.8.2/include/c++/4.8.2/string:40,
                 from ${TRILINOS_SRC_DIR}/packages/teuchos/core/src/Teuchos_ConfigDefs.hpp:84,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_ConfigDefs.hpp:82,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject_decl.hpp:45,
                 from ${TRILINOS_SRC_DIR}/CHECKIN/MPI_DEBUG_KOKKOS_REFACTOR/packages/tpetra/src/Tpetra_DistObject.hpp:1,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject.cpp:44:
${PKG_DIR}/gcc-4.8.2/include/c++/4.8.2/bits/stl_pair.h:276:5: note: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^
${PKG_DIR}/gcc-4.8.2/include/c++/4.8.2/bits/stl_pair.h:276:5: note:   template argument deduction/substitution failed:
In file included from ${TRILINOS_SRC_DIR}/packages/kokkos/compat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:24:0,
                 from ${TRILINOS_SRC_DIR}/packages/kokkos/classic/NodeAPI/Kokkos_DefaultNode.hpp:61,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_Map_decl.hpp:45,
                 from ${TRILINOS_SRC_DIR}/CHECKIN/MPI_DEBUG_KOKKOS_REFACTOR/packages/tpetra/src/Tpetra_Map.hpp:1,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject_decl.hpp:46,
                 from ${TRILINOS_SRC_DIR}/CHECKIN/MPI_DEBUG_KOKKOS_REFACTOR/packages/tpetra/src/Tpetra_DistObject.hpp:1,
                 from ${TRILINOS_SRC_DIR}/packages/tpetra/src/Tpetra_DistObject.cpp:44:
${TRILINOS_SRC_DIR}/packages/kokkos/compat/src/KokkosCompat_View.hpp:193:65: note:   cannot convert ‘offset’ (type ‘long unsigned int’) to type ‘long unsigned int&&’