SUMMARY:  attempting, blind and in the dark, to fix Tpetra build error for Windows platform
     CHECKLIST
     ---------

CVS: ADDING FILES:
     1) Did you 'cvs add' all new files and directories [Y:N:N/A]?  n/a

CVS:    NOTE: Packages that use globbing can skip 2
     2) Did you add new source files to a CMakeLists.txt file [Y:N:N/A]?  n/a

CVS: MODIFYING FILES:
     3)  Did you modify or add any source or build system files?  yes
CVS:     If yes:  (if no, delete lines 3a, 3b, and 3c, and skip 5.)
     3a) Did you rebuild the libraries and executables?  yes
     3b) Did you rerun the test suite on the packages that you changed and
         all packages that depend on the modified packages?  yes
     3c) Did you change the required or optional dependencies for any
         package?  n/a
CVS:     If yes, check in from the Trilinos level to update CMake XML and HTML
CVS:     dependency files.

CVS: CHECKIN:
CVS: 4) Perform the checkin.
CVS:
CVS: POST-CHECKIN:
CVS: 5) Do a 'cvs update' on a different working directory of Trilinos and
CVS:    rebuild at least the packages that you modified.

Errors from Sept 2 build, in head branch, should also exist in 10-0 release branch:
C:\T\SERIAL_RELEASE_PS\Trilinos\packages\tpetra\src\Tpetra_CrsGraph.hpp(1264) : warning C4800: 'char' : forcing value to bool 'true' or 'false' (performance warning)
C:\T\SERIAL_RELEASE_PS\Trilinos\packages\tpetra\src\Tpetra_CrsGraph.hpp(1215) : while compiling class template member function 'void Tpetra::CrsGraph<LocalOrdinal,GlobalOrdinal,Node>::globalAssemble(void)'
    with
    [
    LocalOrdinal=short,
    GlobalOrdinal=int,
    Node=`anonymous-namespace'::Node
    ]

C:\T\SERIAL_RELEASE_PS\Trilinos\packages\tpetra\src\Tpetra_CrsGraph.hpp(542) : error C2059: syntax error : 'template'
C:\T\SERIAL_RELEASE_PS\Trilinos\packages\tpetra\src\Tpetra_CrsGraph.hpp(524) : while compiling class template member function 'void Tpetra::CrsGraph<LocalOrdinal,GlobalOrdinal,Node>::allocateIndices(Tpetra::CrsGraph<LocalOrdinal,GlobalOrdinal,Node>::AllocateLocalGlobal)'
    with
    [
    LocalOrdinal=short,
    GlobalOrdinal=int,
    Node=`anonymous-namespace'::Node
    ]

Also, some conversions in Import/Export unit tests that should be corrected via static_cast<>.


(checklist version 2009-07-14)




=============================
Automated status information
=============================


Thu Sep  3 09:07:40 MDT 2009



-------------------
Summary of Results:
-------------------


MPI_DEBUG Results:
------------------------

  passed : Trilinos/MPI_DEBUG: passed=21,notpassed=0

  Thu Sep  3 09:05:47 MDT 2009

  Enabled Packages: Tpetra
  Hostname: s903186.sandia.gov
  Source Dir: /Users/cgbaker/Trilinos10
  Build Dir: /Users/cgbaker/TBUILDS/CHECKIN/MPI_DEBUG

  CMake Cache Varibles: -DTPL_ENABLE_MPI:BOOL=ON -DTrilinos_ENABLE_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RELEASE -DTrilinos_ENABLE_DEBUG:BOOL=ON -DTrilinos_ENABLE_CHECKED_STL:BOOL=ON -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DTrilinos_ENABLE_Fortran:BOOL=OFF -DTrilinos_ENABLE_Epetra:BOOL=OFF -DTrilinos_ENABLE_Zoltan:BOOL=OFF -DTrilinos_ENABLE_Isorropia:BOOL=OFF -DTrilinos_ENABLE_AztecOO:BOOL=OFF -DTrilinos_ENABLE_Galeri:BOOL=OFF -DTrilinos_ENABLE_Amesos:BOOL=OFF -DTrilinos_ENABLE_Ifpack:BOOL=OFF -DTrilinos_ENABLE_ML:BOOL=OFF -DTrilinos_ENABLE_Thyra:BOOL=OFF -DTrilinos_ENABLE_NOX:BOOL=OFF -DTrilinos_ENABLE_Tpetra:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON

  CTest Options: -j4

  Update: Passed (0.262435984612 min)
  Configure: Passed (0.14001506567 min)
  Build: Passed (0.800713686148 min)
  Test: Passed (0.175743730863 min)

  Test summary:
  -------------

  100% tests passed, 0 tests failed out of 21

  Total CPU time =   0.00 sec


  Final:
  ------

  Total time for MPI_DEBUG = 1.1177992185 minutes


SERIAL_RELEASE Results:
------------------------

  passed : Trilinos/SERIAL_RELEASE: passed=22,notpassed=0

  Thu Sep  3 09:06:36 MDT 2009

  Enabled Packages: Tpetra
  Hostname: s903186.sandia.gov
  Source Dir: /Users/cgbaker/Trilinos10
  Build Dir: /Users/cgbaker/TBUILDS/CHECKIN/SERIAL_RELEASE

  CMake Cache Varibles: -DTrilinos_ENABLE_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RELEASE -DTrilinos_ENABLE_DEBUG:BOOL=OFF -DTrilinos_ENABLE_CHECKED_STL:BOOL=OFF -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DTrilinos_ENABLE_Fortran:BOOL=OFF -DTrilinos_ENABLE_Epetra:BOOL=OFF -DTrilinos_ENABLE_Zoltan:BOOL=OFF -DTrilinos_ENABLE_Isorropia:BOOL=OFF -DTrilinos_ENABLE_AztecOO:BOOL=OFF -DTrilinos_ENABLE_Galeri:BOOL=OFF -DTrilinos_ENABLE_Amesos:BOOL=OFF -DTrilinos_ENABLE_Ifpack:BOOL=OFF -DTrilinos_ENABLE_ML:BOOL=OFF -DTrilinos_ENABLE_Thyra:BOOL=OFF -DTrilinos_ENABLE_NOX:BOOL=OFF -DTrilinos_ENABLE_Tpetra:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON

  CTest Options: -j4

  Update: Passed (0.262435984612 min)
  Configure: Passed (0.140830397606 min)
  Build: Passed (0.631689850489 min)
  Test: Passed (0.0353158831596 min)

  Test summary:
  -------------

  100% tests passed, 0 tests failed out of 22

  Total CPU time =   0.00 sec


  Final:
  ------

  Total time for SERIAL_RELEASE = 0.809778483709 minutes