Revert "stk_mesh: Remove all uses of backwards compatibility layers in non-percept stk products"
This reverts commit 57b4c0bc9f5a8735cf3c31f44ce040a61d894fa3.

All adagio tests were failing with this commit, with the following message:

SIERRA execution failed during execute with the following exception:
Error occured at: stk_mesh/stk_mesh/base/Entity.tcc:269
Error: template <class SharedAttr> void Entity::init_fmwk(..) has been deprecated

    while running Procedure::read_mesh_input() procedure 'Apst_Procedure'
  exception thrown from framework/src/framewk/Fmwk_Domain.C:279
    from sierra::Fmwk::create_meshobj(...)
    from MeshObjRoster::create( const Id & input_global_id , const MeshObjSharedAttr & input_attr , const UInt relation_len , const Relation relation[] , const bool check_duplicate_by_relation , const bool investigate_parallel , const Int input_owner_proc )
    from sierra::Frio::MeshReader::region_io(IOBroker::FieldList &additional_fields )
    from sierra::Fmwk::Region::process_input_mesh()
    from sierra::Fmwk::Procedure::read_mesh_input()
    from sierra::Fmwk::Domain::execute()

(From Sierra)